INFO - 2022-01-04 19:46:07,418 - new_apply_order.py[line:892]: 开始第 aceloan【1】次进件……
ERROR - 2022-01-04 19:46:07,727 - new_apply_order.py[line:938]: name 'cfg_' is not defined
ERROR - 2022-01-04 19:46:07,735 - new_apply_order.py[line:939]: None
