INFO - 2021-12-02 14:06:54,163 - new_apply_order.py[line:882]: 开始第 ikash【1】次进件……
INFO - 2021-12-02 14:06:54,163 - new_apply_order.py[line:84]: ======【ke测试环境】生成手机号：738425214 ======
INFO - 2021-12-02 14:06:54,783 - new_apply_order.py[line:97]: 738425214 检测用户存在成功！
INFO - 2021-12-02 14:06:54,983 - new_apply_order.py[line:106]: 738425214 短信发送成功！
INFO - 2021-12-02 14:06:55,272 - new_apply_order.py[line:119]: 738425214 注册成功！
INFO - 2021-12-02 14:06:55,374 - new_apply_order.py[line:135]: 738425214 登录短信发送成功！
INFO - 2021-12-02 14:06:55,868 - new_apply_order.py[line:145]: userId=6237677188080869376,mobile=738425214,token=166a0290de34bc93d5e110158bb43016 登录成功
INFO - 2021-12-02 14:06:56,762 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-12-02 14:06:57,005 - new_apply_order.py[line:232]: 联系人信息提交成功！
INFO - 2021-12-02 14:06:58,332 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-12-02 14:06:58,347 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-12-02 14:06:58,356 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-12-02 14:06:58,870 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-12-02 14:06:58,988 - new_apply_order.py[line:352]: 视频认证通过！
ERROR - 2021-12-02 14:06:59,246 - new_apply_order.py[line:579]: 绑卡失败！{"code":"60001004","msg":"The OTP has expired.please regenerate OTP to try again","data":null}
INFO - 2021-12-02 14:06:59,805 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-12-02 14:07:00,885 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-12-02 14:07:01,466 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:07:01,540 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-12-02 14:07:04,662 - new_apply_order.py[line:669]: 获取token成功！token=bearer 79c1b5ea-9238-47e0-a22f-ee222d185aac！
INFO - 2021-12-02 14:07:05,059 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:07:06,127 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-12-02 14:07:06,148 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-12-02 14:07:06,160 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-12-02 14:07:07,533 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:07:07,548 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-12-02 14:07:07,554 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-12-02 14:07:07,922 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:07:08,237 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-12-02 14:07:09,252 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-12-02 14:07:09,253 - new_apply_order.py[line:802]: {'app': 'ikash', 'loan_order_id': '1466287752848609280', 'mobile': '738425214', 'order_status': 30}
INFO - 2021-12-02 14:07:09,253 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-12-02 14:07:10,266 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-12-02 14:07:10,267 - new_apply_order.py[line:802]: {'app': 'ikash', 'loan_order_id': '1466287752848609280', 'mobile': '738425214', 'order_status': 30}
INFO - 2021-12-02 14:07:10,267 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-12-02 14:07:11,281 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-12-02 14:07:11,282 - new_apply_order.py[line:802]: {'app': 'ikash', 'loan_order_id': '1466287752848609280', 'mobile': '738425214', 'order_status': 30}
INFO - 2021-12-02 14:07:11,282 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-12-02 14:07:12,295 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-12-02 14:07:12,296 - new_apply_order.py[line:802]: {'app': 'ikash', 'loan_order_id': '1466287752848609280', 'mobile': '738425214', 'order_status': 30}
INFO - 2021-12-02 14:07:12,296 - new_apply_order.py[line:905]: 校验重试查询第5次
