INFO - 2021-10-13 11:16:03,306 - new_apply_order.py[line:798]: 开始第 monni【1】次进件……
INFO - 2021-10-13 11:16:03,306 - new_apply_order.py[line:82]: ======【co测试环境】生成手机号：3634094963 ======
INFO - 2021-10-13 11:16:03,688 - new_apply_order.py[line:95]: 3634094963 检测用户存在成功！
INFO - 2021-10-13 11:16:03,747 - new_apply_order.py[line:104]: 3634094963 短信发送成功！
INFO - 2021-10-13 11:16:03,805 - new_apply_order.py[line:117]: 3634094963 注册成功！
INFO - 2021-10-13 11:16:03,922 - new_apply_order.py[line:133]: 3634094963 登录短信发送成功！
INFO - 2021-10-13 11:16:03,987 - new_apply_order.py[line:143]: userId=4961223597365665792,mobile=3634094963,token=519536c2d3369fe0ce962a0c9e42ea1e 登录成功
INFO - 2021-10-13 11:16:04,095 - new_apply_order.py[line:208]: 个人信息提交成功！
INFO - 2021-10-13 11:16:04,372 - new_apply_order.py[line:241]: 创建预审订单成功！
INFO - 2021-10-13 11:16:04,394 - new_apply_order.py[line:249]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-13 11:16:04,414 - new_apply_order.py[line:252]: 更新初始额度！更新条数 1
INFO - 2021-10-13 11:16:04,753 - new_apply_order.py[line:269]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-13 11:16:04,811 - new_apply_order.py[line:279]: 视频认证通过！
INFO - 2021-10-13 11:16:05,904 - new_apply_order.py[line:367]: curp上传成功!
INFO - 2021-10-13 11:16:06,011 - new_apply_order.py[line:376]: curp_rfc校验通过！
INFO - 2021-10-13 11:16:06,572 - new_apply_order.py[line:512]: 不绑卡成功跳过！
INFO - 2021-10-13 11:16:06,760 - new_apply_order.py[line:528]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-10-13 11:16:07,806 - new_apply_order.py[line:534]: 订单表更新1条，信审更新1条
INFO - 2021-10-13 11:16:08,345 - new_apply_order.py[line:548]: 查询loan_order_id成功！
INFO - 2021-10-13 11:16:08,380 - new_apply_order.py[line:563]: 订单回调复审通过成功！
INFO - 2021-10-13 11:16:09,202 - new_apply_order.py[line:585]: 获取token成功！token=bearer ca76a2a1-8b53-4135-a34d-afe8a2d75cee！
INFO - 2021-10-13 11:16:09,784 - new_apply_order.py[line:548]: 查询loan_order_id成功！
INFO - 2021-10-13 11:16:10,123 - new_apply_order.py[line:603]: 后台已触发放款成功！
INFO - 2021-10-13 11:16:10,135 - new_apply_order.py[line:617]: xxl_job web 登录成功！
INFO - 2021-10-13 11:16:10,146 - new_apply_order.py[line:633]: xxl_job 放款准备作业执行成功！
INFO - 2021-10-13 11:16:11,699 - new_apply_order.py[line:548]: 查询loan_order_id成功！
INFO - 2021-10-13 11:16:11,720 - new_apply_order.py[line:641]: 修改放款准备完成时间成功！
INFO - 2021-10-13 11:16:11,725 - new_apply_order.py[line:649]: xxl_job 放款完成作业执行成功！
INFO - 2021-10-13 11:16:12,030 - new_apply_order.py[line:821]: 校验重试查询第1次
ERROR - 2021-10-13 11:16:13,041 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:13,041 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:13,546 - new_apply_order.py[line:821]: 校验重试查询第2次
ERROR - 2021-10-13 11:16:14,560 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:14,560 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:15,068 - new_apply_order.py[line:821]: 校验重试查询第3次
ERROR - 2021-10-13 11:16:16,080 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:16,081 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:16,586 - new_apply_order.py[line:821]: 校验重试查询第4次
ERROR - 2021-10-13 11:16:17,598 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:17,598 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:18,104 - new_apply_order.py[line:821]: 校验重试查询第5次
ERROR - 2021-10-13 11:16:19,118 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:19,119 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:19,623 - new_apply_order.py[line:821]: 校验重试查询第6次
ERROR - 2021-10-13 11:16:20,637 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:20,637 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:21,143 - new_apply_order.py[line:821]: 校验重试查询第7次
ERROR - 2021-10-13 11:16:22,158 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:22,159 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:22,666 - new_apply_order.py[line:821]: 校验重试查询第8次
ERROR - 2021-10-13 11:16:23,679 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:23,680 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:24,185 - new_apply_order.py[line:821]: 校验重试查询第9次
ERROR - 2021-10-13 11:16:25,198 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:25,198 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:25,701 - new_apply_order.py[line:821]: 校验重试查询第10次
ERROR - 2021-10-13 11:16:26,714 - new_apply_order.py[line:717]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-10-13 11:16:26,714 - new_apply_order.py[line:718]: {'app': 'monni', 'loan_order_id': '1448125355240853504', 'mobile': '3634094963', 'order_status': 35}
INFO - 2021-10-13 11:16:27,218 - new_apply_order.py[line:838]: ===========完成第【1】次进件===========
INFO - 2021-10-13 11:16:27,218 - new_apply_order.py[line:841]: ======完成第【1】次进件,耗时23.91s=====
INFO - 2021-10-13 11:16:27,223 - new_apply_order.py[line:798]: 开始第 ikash【1】次进件……
INFO - 2021-10-13 11:16:27,224 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：734094987 ======
INFO - 2021-10-13 11:16:27,594 - new_apply_order.py[line:95]: 734094987 检测用户存在成功！
INFO - 2021-10-13 11:16:27,651 - new_apply_order.py[line:104]: 734094987 短信发送成功！
INFO - 2021-10-13 11:16:27,698 - new_apply_order.py[line:117]: 734094987 注册成功！
INFO - 2021-10-13 11:16:27,756 - new_apply_order.py[line:133]: 734094987 登录短信发送成功！
INFO - 2021-10-13 11:16:27,809 - new_apply_order.py[line:143]: userId=6219514897629192192,mobile=734094987,token=04115a76804f9f407494356a3345f516 登录成功
INFO - 2021-10-13 11:16:27,920 - new_apply_order.py[line:208]: 个人信息提交成功！
INFO - 2021-10-13 11:16:27,988 - new_apply_order.py[line:228]: 联系人信息提交成功！
INFO - 2021-10-13 11:16:28,440 - new_apply_order.py[line:241]: 创建预审订单成功！
INFO - 2021-10-13 11:16:28,450 - new_apply_order.py[line:249]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-13 11:16:28,458 - new_apply_order.py[line:252]: 更新初始额度！更新条数 1
INFO - 2021-10-13 11:16:28,756 - new_apply_order.py[line:269]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-13 11:16:28,795 - new_apply_order.py[line:279]: 视频认证通过！
INFO - 2021-10-13 11:16:29,101 - new_apply_order.py[line:503]: 绑卡成功！
ERROR - 2021-10-13 11:16:29,274 - new_apply_order.py[line:536]: {"code":"50001012","msg":"The loan amount has increased, please pull down to refresh to get.","data":null}
ERROR - 2021-10-13 11:16:29,615 - new_apply_order.py[line:844]: 'NoneType' object is not subscriptable
ERROR - 2021-10-13 11:16:29,617 - new_apply_order.py[line:845]: None
INFO - 2021-10-13 11:16:29,620 - new_apply_order.py[line:798]: 开始第 kencash【1】次进件……
INFO - 2021-10-13 11:16:29,621 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：734094989 ======
INFO - 2021-10-13 11:16:29,972 - new_apply_order.py[line:95]: 734094989 检测用户存在成功！
INFO - 2021-10-13 11:16:30,023 - new_apply_order.py[line:104]: 734094989 短信发送成功！
INFO - 2021-10-13 11:16:30,062 - new_apply_order.py[line:117]: 734094989 注册成功！
INFO - 2021-10-13 11:16:30,113 - new_apply_order.py[line:133]: 734094989 登录短信发送成功！
INFO - 2021-10-13 11:16:30,164 - new_apply_order.py[line:143]: userId=6219514907548721152,mobile=734094989,token=c1b7823c38b577f12e42009cefadbf54 登录成功
INFO - 2021-10-13 11:16:30,282 - new_apply_order.py[line:208]: 个人信息提交成功！
INFO - 2021-10-13 11:16:30,335 - new_apply_order.py[line:228]: 联系人信息提交成功！
INFO - 2021-10-13 11:16:30,563 - new_apply_order.py[line:241]: 创建预审订单成功！
INFO - 2021-10-13 11:16:30,579 - new_apply_order.py[line:249]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-13 11:16:30,593 - new_apply_order.py[line:252]: 更新初始额度！更新条数 1
INFO - 2021-10-13 11:16:30,884 - new_apply_order.py[line:269]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-13 11:16:30,929 - new_apply_order.py[line:279]: 视频认证通过！
INFO - 2021-10-13 11:16:31,245 - new_apply_order.py[line:503]: 绑卡成功！
ERROR - 2021-10-13 11:16:31,418 - new_apply_order.py[line:536]: {"code":"50001012","msg":"The loan amount has increased, please pull down to refresh to get.","data":null}
ERROR - 2021-10-13 11:16:31,751 - new_apply_order.py[line:844]: 'NoneType' object is not subscriptable
ERROR - 2021-10-13 11:16:31,752 - new_apply_order.py[line:845]: None
INFO - 2021-10-13 11:16:31,755 - new_apply_order.py[line:798]: 开始第 oranch【1】次进件……
INFO - 2021-10-13 11:16:31,756 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：734094991 ======
INFO - 2021-10-13 11:16:32,105 - new_apply_order.py[line:95]: 734094991 检测用户存在成功！
INFO - 2021-10-13 11:16:32,159 - new_apply_order.py[line:104]: 734094991 短信发送成功！
INFO - 2021-10-13 11:16:32,204 - new_apply_order.py[line:117]: 734094991 注册成功！
INFO - 2021-10-13 11:16:32,253 - new_apply_order.py[line:133]: 734094991 登录短信发送成功！
INFO - 2021-10-13 11:16:32,302 - new_apply_order.py[line:143]: userId=6219514916524531712,mobile=734094991,token=fc469dc6c519e28314e20a911a1f85e7 登录成功
INFO - 2021-10-13 11:16:32,399 - new_apply_order.py[line:208]: 个人信息提交成功！
INFO - 2021-10-13 11:16:32,463 - new_apply_order.py[line:228]: 联系人信息提交成功！
INFO - 2021-10-13 11:16:32,673 - new_apply_order.py[line:241]: 创建预审订单成功！
INFO - 2021-10-13 11:16:32,682 - new_apply_order.py[line:249]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-13 11:16:32,689 - new_apply_order.py[line:252]: 更新初始额度！更新条数 1
INFO - 2021-10-13 11:16:32,933 - new_apply_order.py[line:269]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-13 11:16:32,970 - new_apply_order.py[line:279]: 视频认证通过！
INFO - 2021-10-13 11:16:33,274 - new_apply_order.py[line:503]: 绑卡成功！
ERROR - 2021-10-13 11:16:33,414 - new_apply_order.py[line:536]: {"code":"50001012","msg":"The loan amount has increased, please pull down to refresh to get.","data":null}
ERROR - 2021-10-13 11:16:33,749 - new_apply_order.py[line:844]: 'NoneType' object is not subscriptable
ERROR - 2021-10-13 11:16:33,750 - new_apply_order.py[line:845]: None
INFO - 2021-10-13 11:16:33,753 - new_apply_order.py[line:798]: 开始第 faikash【1】次进件……
INFO - 2021-10-13 11:16:33,754 - new_apply_order.py[line:82]: ======【ke测试环境】生成手机号：734094993 ======
INFO - 2021-10-13 11:16:34,102 - new_apply_order.py[line:95]: 734094993 检测用户存在成功！
INFO - 2021-10-13 11:16:34,167 - new_apply_order.py[line:104]: 734094993 短信发送成功！
INFO - 2021-10-13 11:16:34,230 - new_apply_order.py[line:117]: 734094993 注册成功！
INFO - 2021-10-13 11:16:34,283 - new_apply_order.py[line:133]: 734094993 登录短信发送成功！
INFO - 2021-10-13 11:16:34,348 - new_apply_order.py[line:143]: userId=6219514924946694144,mobile=734094993,token=750423b14c9857a2538214d89c5632a0 登录成功
INFO - 2021-10-13 11:16:34,466 - new_apply_order.py[line:208]: 个人信息提交成功！
INFO - 2021-10-13 11:16:34,541 - new_apply_order.py[line:228]: 联系人信息提交成功！
INFO - 2021-10-13 11:16:34,808 - new_apply_order.py[line:241]: 创建预审订单成功！
INFO - 2021-10-13 11:16:34,826 - new_apply_order.py[line:249]: 预审状态修改为通过,更新条数 1
INFO - 2021-10-13 11:16:34,842 - new_apply_order.py[line:252]: 更新初始额度！更新条数 1
INFO - 2021-10-13 11:16:35,130 - new_apply_order.py[line:269]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-10-13 11:16:35,173 - new_apply_order.py[line:279]: 视频认证通过！
INFO - 2021-10-13 11:16:35,495 - new_apply_order.py[line:503]: 绑卡成功！
ERROR - 2021-10-13 11:16:35,630 - new_apply_order.py[line:536]: {"code":"50001012","msg":"The loan amount has increased, please pull down to refresh to get.","data":null}
ERROR - 2021-10-13 11:16:35,965 - new_apply_order.py[line:844]: 'NoneType' object is not subscriptable
ERROR - 2021-10-13 11:16:35,966 - new_apply_order.py[line:845]: None
