INFO - 2021-11-02 17:50:33,305 - new_apply_order.py[line:882]: 开始第 ncredit【1】次进件……
INFO - 2021-11-02 17:50:33,306 - new_apply_order.py[line:84]: ======【nga测试环境】生成手机号：01635846633 ======
INFO - 2021-11-02 17:50:33,674 - new_apply_order.py[line:97]: 01635846633 检测用户存在成功！
INFO - 2021-11-02 17:50:33,722 - new_apply_order.py[line:106]: 01635846633 短信发送成功！
INFO - 2021-11-02 17:50:33,764 - new_apply_order.py[line:119]: 01635846633 注册成功！
INFO - 2021-11-02 17:50:33,818 - new_apply_order.py[line:135]: 01635846633 登录短信发送成功！
INFO - 2021-11-02 17:50:33,862 - new_apply_order.py[line:145]: userId=6226861833466159104,mobile=01635846633,token=f9dd3b6f75e8480983113cf34a5e75a6 登录成功
INFO - 2021-11-02 17:50:33,948 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-11-02 17:50:33,999 - new_apply_order.py[line:223]: 联系人信息提交成功！
INFO - 2021-11-02 17:50:34,299 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-11-02 17:50:34,314 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-11-02 17:50:34,327 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-11-02 17:50:34,585 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-11-02 17:50:34,622 - new_apply_order.py[line:352]: 视频认证通过！
INFO - 2021-11-02 17:50:35,712 - new_apply_order.py[line:510]: bvn和银行卡绑卡认证通过！
INFO - 2021-11-02 17:50:36,018 - new_apply_order.py[line:561]: user更新1条
INFO - 2021-11-02 17:50:36,247 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-11-02 17:50:37,294 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-11-02 17:50:37,662 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-02 17:50:37,711 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-11-02 17:50:38,477 - new_apply_order.py[line:669]: 获取token成功！token=bearer be80aa3b-ee11-4151-b49d-576648d268e6！
INFO - 2021-11-02 17:50:38,825 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-02 17:50:39,131 - new_apply_order.py[line:687]: 后台已触发放款成功！
ERROR - 2021-11-02 17:51:05,053 - new_apply_order.py[line:928]: HTTPConnectionPool(host='172.20.240.225', port=8066): Max retries exceeded with url: /xxl-job-admin/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9c9effb7f0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
ERROR - 2021-11-02 17:51:05,070 - new_apply_order.py[line:929]: None
